### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by pablixhd** [YannickNoelStephanKuhn/EP-BOLFI#6]
Hi,

Thanks for the project. I've encountered issues following the installation instructions, finding them a bit vague. Despite having Python 3.9.13 and all dependencies installed on Windows, and also trying on Linux, I run into errors due to missing Python modules, causing script failures. Could a more detailed installation guide be provided?

Thanks :)

This is what i get in the shell in vs-code.
![image](https://github.com/YannickNoelStephanKuhn/EP-BOLFI/assets/75529041/ef01fad8-368b-4be1-a228-baa339121685)

This is my folder structure
(MAIN FOLDER)
![image](https://github.com/YannickNoelStephanKuhn/EP-BOLFI/assets/75529041/477f4c87-cc9f-4930-b40a-dd1896f47666)
(Python folder)
![image](https://github.com/YannickNoelStephanKuhn/EP-BOLFI/assets/75529041/00cd3d1c-90cf-4355-9177-3d67056639bc)

**Comment by YannickNoelStephanKuhn** [comment]
Hi, that is not a missing module issue, that is Windows PowerShell being unable to display the character √. Something I only noticed after uploading the repo, as it works fine on Unix machines.

It's lines 144 and 146 in the script you tried to run. Since you seem to have installed the repo from source, you may want to do a Ctrl-Shift-F in VSCode to search and replace all instances of √ with something like "sqrt". The next release will not have the √ symbols anymore. Sorry for the inconvenience.

**Comment by YannickNoelStephanKuhn** [comment]
Fixed via https://github.com/YannickNoelStephanKuhn/EP-BOLFI/commit/f0452c81953420e9a5dd92edf0fb8f3a6fd4c7ec
